apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
    - port: 80
  clusterIP: None
  selector:
    app: nginx-app-pod

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-app-pod
    spec:
      containers:
        - name: my-container
          image: nginx:1.23.1
          volumeMounts:
            - name: my-volume-persistente
              mountPath: /usr/share/nginx/html
  selector:
    matchLabels:
      app: nginx-app-pod
  serviceName: "svc-sts"
  volumeClaimTemplates:
    - metadata:
        name: my-volume-persistente
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi