apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps
  labels:
    kubernetes.io/service-name: my-endpoints-service
addressType: IPv4
endpoints:
  - addresses:
      - 10.1.1.99
ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps2
  labels:
    kubernetes.io/service-name: my-endpoints-service
addressType: IPv4
endpoints:
  - addresses:
      - 10.1.1.98
ports:
  - name: http
    port: 80
    protocol: TCP
