apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
  labels:
    app: frontend
spec:
  updateStrategy:
    type: RollingUpdate
    # type: onDelete
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      name: my-pod-webserver
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container-nginx
        image: nginx
      nodeSelector:
        disktype: ssd
  selector:
    matchLabels:
      app: my-app

