apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: prod-nginx
      labels: 
        env: production
    spec:
      containers:
        - name: container-nginx
          image: nginx:alpine
  selector:
    matchLabels:
      env: production
  strategy:
    type: Recreate
  replicas: 10