apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-20T23:57:45Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "459889"
  uid: c2db4034-b8de-45ff-86b8-bdb3cfe2c7a7
spec:
  clusterIP: 10.104.62.246
  clusterIPs:
  - 10.104.62.246
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30159
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}