apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
    - name: redis-container
      image: redis
      resources:
        requests:
          cpu: "400m" # meia cpu
          memory: "64Mi"
        limits:
          cpu: "500m" # meia cpu
          memory: "256Mi"
    - name: apache-container
      image: httpd
      resources:
        requests:
          cpu: "500m" # meia cpu
          memory: "128Mi"
        limits:
          cpu: "1000m" # meia cpu
          memory: "256Mi"