apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
        - name: my-container
          image: busybox
          command:
            - "bin/sh"
            - "-c"
            - "ping -c1 8.8.8.8"
      restartPolicy: Never