apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: redis-pod
      image: redis
      volumeMounts:
        - name: "cache-storage"
          mountPath: "/data"
  volumes:
  - name: cache-storage
    emptyDir: {}
