apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    apps: my-app
    tier: frontend
spec:
  containers:
  - name: my-container-nginx
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-apache
  labels:
    apps: my-app
    tier: frontend
spec:
  containers:
  - name: my-container-apache
    image: httpd