apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfimap
  namespace: default
data:
  #Connection databases config
  database: mysql
  database_uri: mysql://localhost:3306

  #User interface
  font.title: Arial-bold
  backgroud-color: red
  theme_1: clean

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: container-mongo
      image: nginx
      envFrom:
        - configMapRef:
            name: myconfimap
