apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfimap
data:
  #Connection databases config
  database: mongodb
  database_uri: mongodb://localhost:27017

  #User interface
  font.title: Arial
  backgroud-color: red
  theme.1: clean

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: container-mongo
      image: nginx
      envFrom:
        - configMapRef:
            name: myconfimap
