apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: container-mongo
      image: nginx
      envFrom:
        - configMapRef:
            name: myconfimap
      volumeMounts:
        - name: my-vol
          mountPath: "/etc/my-vol"
          readOnly: true
  volumes:
    - name: my-vol
      configMap:
        name: myconfimap