apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: YWRtaW4=
  pass: YWRtaW4xMjM=
stringData:
  username: test
  password: test123

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: container-nginx
      image: nginx
      envFrom:
        - secretRef:
            name: my-secret
      volumeMounts:
        - name: my-vol
          mountPath: "/etc/my-vol"
          readOnly: true
  volumes:
    - name: my-vol
      secret:
        secretName: my-secret