apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: container-nginx
      image: nginx
      envFrom:
        - secretRef:
            name: my-secret
            optional: true #secret opcional
      volumeMounts:
        - name: my-vol
          mountPath: "/etc/my-vol"
          readOnly: true
  volumes:
    - name: my-vol
      secret:
        secretName: my-secret
        optional: true
      