apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: my-pod-webserver
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container-nginx
        image: nginx
  selector:
    matchLabels:
      app: my-app
  replicas: 3
